title:            Setec Astronomy
tagline:          Too Many Secrets
description:      Random rants and musings on nothing in particular
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //blog.setec.io

# Owner/author information
owner:
  name:           Harlan Lieberman-Berg
  avatar:         bio-photo.jpg
  bio:            "Founder of [AdvertiSin](http://www.advertisin.com), ex-Director of Engineering and Operations at [Chitika](http://www.chitika.com), Debian Maintainer, systems design geek, and all around nerd."
  email:          H.LiebermanBerg@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  #twitter:
  facebook:       harlan.liebermanberg
  github:         hlieberman
  linkedin:       hlieberman
  #instagram:
  #lastfm:
  stackexchange: 490619/scrivener
  #tumblr:
  #hmfaysalsocial:
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:

# Analytics and webmaster tools stuff goes here
#google_analytics:
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Posts
    url: /posts/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "assets/less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", ".git"]